/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itson.kaiba.ui;

import java.util.Comparator;
import java.awt.FileDialog;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.table.DefaultTableModel;
import mx.itson.kaiba.entities.AccountHolder;
import mx.itson.kaiba.entities.Transaction;
import mx.itson.kaiba.entities.UsserData;


/**
 *
 * @author MASTER1
 */
public class Account extends javax.swing.JFrame {

    /**
     * Creates new form Account
     */
    public Account() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProduct = new javax.swing.JLabel();
        lblAccountnumber = new javax.swing.JLabel();
        lblcurrency = new javax.swing.JLabel();
        btnSelector = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAccounHolder = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTransactions = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblProduct.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        lblProduct.setForeground(new java.awt.Color(0, 0, 0));
        lblProduct.setText("...");

        lblAccountnumber.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblAccountnumber.setForeground(new java.awt.Color(0, 0, 0));
        lblAccountnumber.setText("...");

        lblcurrency.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblcurrency.setForeground(new java.awt.Color(0, 0, 0));
        lblcurrency.setText("...");

        btnSelector.setText("Start transaction");
        btnSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectorActionPerformed(evt);
            }
        });

        tblAccounHolder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Accoun Holder"
            }
        ));
        jScrollPane1.setViewportView(tblAccounHolder);

        tblTransactions.setBackground(new java.awt.Color(102, 0, 102));
        tblTransactions.setForeground(new java.awt.Color(255, 255, 255));
        tblTransactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date", "Descripcion", "References", "Amount", "Type"
            }
        ));
        jScrollPane3.setViewportView(tblTransactions);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("GALAXYBANK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblProduct, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(lblAccountnumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(782, 782, 782))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblcurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231)
                        .addComponent(btnSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAccountnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblcurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectorActionPerformed
    // Abrir un diálogo para seleccionar un archivo JSON
    FileDialog fileDialog = new FileDialog(this, "Select json file", FileDialog.LOAD);
    fileDialog.setVisible(true);

    String route = fileDialog.getDirectory();
    String archive = fileDialog.getFile();

    if (archive != null) {
        File archivoSeleccionado = new File(route, archive);

        try (BufferedReader reader = new BufferedReader(new FileReader(archivoSeleccionado))) {
            StringBuilder contenidoJson = new StringBuilder();
            String linea;

            // Leer línea por línea el archivo JSON
            while ((linea = reader.readLine()) != null) {
                contenidoJson.append(linea).append("\n");
            }

            String content = contenidoJson.toString();

            // Deserializar el contenido JSON a objeto Java
            Transaction accountStatus = Transaction.deserialize(content);
            AccountHolder holder = accountStatus.getAccountHolder();

            // Mostrar datos generales en etiquetas
            lblProduct.setText(accountStatus.getProduct());
            lblAccountnumber.setText("Número de cuenta: " + accountStatus.getAccountNumber());
            lblcurrency.setText("Moneda: " + accountStatus.getCurrency());
            
            
            

            // Mostrar información del titular de la cuenta
            DefaultTableModel headlineModel = (DefaultTableModel) tblAccounHolder.getModel();
            headlineModel.addRow(new Object[]{ "Código: " + holder.getCode() });
            headlineModel.addRow(new Object[]{ "Nombre: " + holder.getName() });
            headlineModel.addRow(new Object[]{ "Dirección: " + holder.getAddress() });
            headlineModel.addRow(new Object[]{ "Ciudad: " + holder.getCity() });
            headlineModel.addRow(new Object[]{ "RFC: " + holder.getTaxpayerId() });
            headlineModel.addRow(new Object[]{ "Código postal: " + holder.getZipCode() });

            
            
            
            
            // Mostrar lista de transacciones ordenadas por fecha
            DefaultTableModel transactionsModel = (DefaultTableModel) tblTransactions.getModel();
            transactionsModel.setRowCount(0); // Limpiar tabla

            
            
            
            List<UsserData> transactions = new ArrayList<>(accountStatus.getTransactions());
            transactions.sort( Comparator.comparing(UsserData::getDate) );


            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy"); // Formato personalizado

            
            for (UsserData transaccion : transactions) {
                transactionsModel.addRow(new Object[]{
                    dateFormat.format(transaccion.getDate()),
                    transaccion.getDescription(),
                    transaccion.getReference(),
                    "$" + transaccion.getAmount(),
                    transaccion.getType()
                });
            }

        } catch (IOException ex) {
            ex.printStackTrace(); // Manejo básico de errores
        }
    }


    }//GEN-LAST:event_btnSelectorActionPerformed



 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Account().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelector;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAccountnumber;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblcurrency;
    private javax.swing.JTable tblAccounHolder;
    private javax.swing.JTable tblTransactions;
    // End of variables declaration//GEN-END:variables
}
